### ISSUE TITLE
`is invalid` flash message

### ISSUE THREAD

**Issue by smpetrey** [code-and-effect/effective_orders#14]
I only get this flash message when I "Proceed to Checkout" and the effective_orders.rb has the following configuration line set to true: `config.stripe_connect_enabled = true`.

By default it is set to false. I wish to integrate Stripe Connect and can't seem to debug the issue. Any help would be awesome!

**Comment by matt-riemer** [comment]
will look into this today....

**Comment by smpetrey** [comment]
Hello @matt-riemer! While I still do not know what the culprit may be, I did some researching this weekend and perhaps the error has to do with `validates_associated` ?
http://guides.rubyonrails.org/active_record_validations.html#validates-associated

**Comment by matt-riemer** [comment]
Doh, I'm sorry @smpetrey I totally never looked into this...

The 'is invalid' is almost certainly coming from one of the `validates_associated`.  

An `Effective::Order` has many `Effective::OrderItems`.  And it belongs_to a User.  Each `OrderItem` belongs_to an `acts_as_purchasable` object.

So when an Order is validated it's checking `valid?` on 4 different models:

- Is the Effective::Order valid?
- Is each of the Effective::OrderItems valid?
  - Is each of the `acts_as_purchasable` objects valid?
- Is the user itself valid?


You can disable the user validation from the `config/initializers/effective_orders.rb` file.  `config.skip_user_validation = true`

Otherwise, it's possible one of your purchasable objects is invalid?

**Comment by smpetrey** [comment]
So, I dug into my project this week and found a hackish way to provide a more productive error since I couldn't see anything other than _is invalid_...

1. I set `config.stripe_connect_enabled` to `false` in `config/initializers/effective_orders.rb` and started my Rails server
2. Navigated to localhost:3000/orders/new to get to the billing/shipping entry (1st page of checkout, 1 item in the cart)
3. Stopped Rails server, set `config.stripe_connect_enabled` to `true` in `config/initializers/effective_orders.rb`
4. Restart Rails server
5. Went back to the window with localhost:3000/orders/new still open
6. Click on `Save and Continue`

It reloads orders/new and produces a flash message that reads:

`An error has ocurred. Please try again. Message: Validation failed: Order items seller can't be blank, Order items is invalid`

Also the familiar words _is invalid_ populates inline just underneath the Checkout table (image below).

Did I miss a step in the installation of effective_orders? I'm still a noob to rails, but why would my (seller) user be blank? Any direction would be gratefully appreciated! 


*Error messages*
![screen shot 2015-09-16 at 11 13 53 pm](https://cloud.githubusercontent.com/assets/6411509/9924820/d3426122-5cc8-11e5-93e4-1d1ac738f094.png)

**Comment by matt-riemer** [comment]
I think the problem is that your Product, or whatever you're defining as `acts_as_purchasable` needs to have a   `.seller()` method, which returns the User that is selling this product.

This is not documented well at all.   The message it's supposed to give is from:

https://github.com/code-and-effect/effective_orders/blob/master/app/models/concerns/acts_as_purchasable.rb#L84

```
  def seller
    if EffectiveOrders.stripe_connect_enabled
      raise 'acts_as_purchasable object requires the seller be defined to return the User selling this item.  This is only a requirement when using StripeConnect.'
    end
  end
```

But I think higher up in the chain, there must be a `rescue` that is eating this error message and returning `is invalid` instead.

**Comment by matt-riemer** [comment]
Before allowing one of your Users to create a Product for sale, you should check that he has a Stripe Connect account setup and configured, using the built in helper `is_stripe_connect_seller?(user)`

https://github.com/code-and-effect/effective_orders/blob/master/app/helpers/effective_stripe_helper.rb#L6

And then, if that returns false, you should send them to Stripe to set up their StripeConnect account, using the built in helper `link_to_new_stripe_connect_customer`

https://github.com/code-and-effect/effective_orders/blob/master/app/helpers/effective_stripe_helper.rb#L10

**Comment by smpetrey** [comment]
Man, thank you so much!
You're totally right!

I put this in my products model:

```
  def seller
    return User.find(self.user_id)
  end
```

Cleared up the validation errors right away. I can't thank you enough! I was pulling my hair out on that one! And thanks for more of the info regarding Stripe Connect and the built-in helpers! Those are awesome.

**Comment by matt-riemer** [comment]
Glad I could help!! I'm going to add this information to the Stripe Connect documentation at some point :)
